/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "MyWeb": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "RealtimeWS": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "TryOnQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TryOnWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpscaleQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UpscaleWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebSocketConnections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}