import { createGateway } from "@ai-sdk/gateway";
import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { generateText } from "ai";
import type { SQSEvent, SQSRecord } from "aws-lambda";
import { Resource } from "sst";

import {
  generateStyleTips,
  getTryOnForTipGeneration,
} from "@/services/style-tip";
import { updateTryOnResult } from "@/services/try-on";

const s3 = new S3Client({});

const gateway = createGateway({
  apiKey: process.env.AI_GATEWAY_API_KEY,
});

const model = gateway("google/gemini-3-pro-image");

type TryOnJobPayload = {
  tryOnId: string;
  bodyImageUrl: string;
  garmentImageUrl: string;
};

export async function handler(event: SQSEvent): Promise<void> {
  for (const record of event.Records) {
    await processRecord(record);
  }
}

async function processRecord(record: SQSRecord): Promise<void> {
  const payload = JSON.parse(record.body) as TryOnJobPayload;
  const startTime = Date.now();

  console.log("Processing try-on job:", payload.tryOnId);

  // 1. Fetch images as data URLs
  const [bodyImage, garmentImage] = await Promise.all([
    fetchImageAsDataUrl(payload.bodyImageUrl),
    fetchImageAsDataUrl(payload.garmentImageUrl),
  ]);

  // 2. Call Gemini 3 Pro for virtual try-on via AI Gateway
  const result = await generateText({
    model,
    messages: [
      {
        role: "user",
        content: [
          { type: "image", image: bodyImage },
          { type: "image", image: garmentImage },
          {
            type: "text",
            text: `Virtual try-on: Place the garment from the second image onto the person in the first image.
Maintain the person's exact pose, body proportions, and facial features.
Ensure the garment fits naturally with realistic fabric draping and proper lighting.
The result should look like a professional fashion photo.`,
          },
        ],
      },
    ],
    providerOptions: {
      google: {
        responseModalities: ["IMAGE"],
        imageConfig: { aspectRatio: "3:4" },
      },
    },
  });

  // 3. Extract and validate generated image
  const imageFiles =
    result.files?.filter((f) => f.mediaType?.startsWith("image/")) ?? [];

  if (imageFiles.length === 0) {
    await updateTryOnResult(payload.tryOnId, {
      status: "failed",
      errorMessage: "No image generated by the model",
    });
    throw new Error("No image generated by the model");
  }

  const generatedImage = imageFiles[0];

  // 4. Upload result to S3
  const resultKey = `try-ons/${payload.tryOnId}/result.png`;
  const imageBuffer = Buffer.from(generatedImage.base64, "base64");

  await s3.send(
    new PutObjectCommand({
      Bucket: Resource.MediaBucket.name,
      Key: resultKey,
      Body: imageBuffer,
      ContentType: generatedImage.mediaType ?? "image/png",
    })
  );

  const processingMs = Date.now() - startTime;
  console.log(`Try-on ${payload.tryOnId} completed in ${processingMs}ms`);

  // 5. Update database with result
  await updateTryOnResult(payload.tryOnId, {
    status: "completed",
    resultKey,
    processingMs,
  });

  // 6. Generate style tips
  try {
    const tryOnData = await getTryOnForTipGeneration(payload.tryOnId);

    if (tryOnData) {
      await generateStyleTips({
        tryOnId: payload.tryOnId,
        garmentName: tryOnData.garment.name,
        garmentCategory: tryOnData.garment.category,
        garmentDescription: tryOnData.garment.description,
        garmentColors: tryOnData.garment.colors,
        bodyProfileFitPreference: tryOnData.bodyProfile.fitPreference,
      });
      console.log(`Style tips generated for try-on ${payload.tryOnId}`);
    }
  } catch (error) {
    console.error(
      `Failed to generate style tips for ${payload.tryOnId}:`,
      error
    );
  }
}

function getMimeTypeFromKey(key: string): string {
  const ext = key.split(".").pop()?.toLowerCase();
  const mimeTypes: Record<string, string> = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    webp: "image/webp",
    gif: "image/gif",
  };
  return mimeTypes[ext ?? ""] ?? "image/jpeg";
}

async function fetchImageAsDataUrl(url: string): Promise<string> {
  // If S3 key, fetch from bucket
  if (url.startsWith("profiles/") || url.startsWith("garments/")) {
    const response = await s3.send(
      new GetObjectCommand({
        Bucket: Resource.MediaBucket.name,
        Key: url,
      })
    );
    const bytes = await response.Body?.transformToByteArray();
    if (!bytes) throw new Error(`Failed to fetch image from S3: ${url}`);
    const base64 = Buffer.from(bytes).toString("base64");
    const mimeType = getMimeTypeFromKey(url);
    return `data:${mimeType};base64,${base64}`;
  }

  // Otherwise fetch from URL
  const response = await fetch(url);
  const buffer = await response.arrayBuffer();
  const base64 = Buffer.from(buffer).toString("base64");
  const contentType = response.headers.get("content-type") ?? "image/jpeg";
  return `data:${contentType};base64,${base64}`;
}
