import { createGateway } from "@ai-sdk/gateway";
import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { generateText } from "ai";
import type { SQSEvent, SQSRecord } from "aws-lambda";
import { Resource } from "sst";

import { publish } from "@/lib/websocket-publisher";
import {
  generateStyleTips,
  getTryOnForTipGeneration,
} from "@/services/style-tip";
import { updateTryOnResult } from "@/services/try-on";

const s3 = new S3Client({});

const gateway = createGateway({
  apiKey: process.env.AI_GATEWAY_API_KEY,
});

const model = gateway("google/gemini-3-pro-image");

type TryOnJobPayload = {
  tryOnId: string;
  userId: string;
  bodyImageUrl: string;
  garmentImageUrl: string;
};

export async function handler(event: SQSEvent): Promise<void> {
  for (const record of event.Records) {
    await processRecord(record);
  }
}

async function processRecord(record: SQSRecord): Promise<void> {
  const payload = JSON.parse(record.body) as TryOnJobPayload;
  const { tryOnId, userId } = payload;
  const startTime = Date.now();

  console.log("Processing try-on job:", tryOnId);

  // Publish queued event
  await publish({
    type: "progress",
    tryOnId,
    userId,
    stage: "queued",
    timestamp: Date.now(),
  });

  // 1. Fetch images as data URLs
  await publish({
    type: "progress",
    tryOnId,
    userId,
    stage: "fetching_images",
    timestamp: Date.now(),
  });

  const [bodyImage, garmentImage] = await Promise.all([
    fetchImageAsDataUrl(payload.bodyImageUrl),
    fetchImageAsDataUrl(payload.garmentImageUrl),
  ]);

  // 2. Call Gemini 3 Pro for virtual try-on via AI Gateway
  await publish({
    type: "progress",
    tryOnId,
    userId,
    stage: "generating",
    timestamp: Date.now(),
  });

  const result = await generateText({
    model,
    messages: [
      {
        role: "user",
        content: [
          { type: "image", image: bodyImage },
          { type: "image", image: garmentImage },
          {
            type: "text",
            text: `Virtual try-on: Place the garment from the second image onto the person in the first image.
Maintain the person's exact pose, body proportions, and facial features.
Ensure the garment fits naturally with realistic fabric draping and proper lighting.
The result should look like a professional fashion photo.`,
          },
        ],
      },
    ],
    providerOptions: {
      google: {
        responseModalities: ["IMAGE"],
        imageConfig: { aspectRatio: "3:4" },
      },
    },
  });

  // 3. Extract and validate generated image
  const imageFiles =
    result.files?.filter((f) => f.mediaType?.startsWith("image/")) ?? [];

  if (imageFiles.length === 0) {
    await updateTryOnResult(tryOnId, {
      status: "failed",
      errorMessage: "No image generated by the model",
    });
    await publish({
      type: "progress",
      tryOnId,
      userId,
      stage: "failed",
      timestamp: Date.now(),
      error: "No image generated by the model",
    });
    throw new Error("No image generated by the model");
  }

  const generatedImage = imageFiles[0];

  // 4. Upload result to S3
  await publish({
    type: "progress",
    tryOnId,
    userId,
    stage: "uploading",
    timestamp: Date.now(),
  });

  const resultKey = `try-ons/${tryOnId}/result.png`;
  const imageBuffer = Buffer.from(generatedImage.base64, "base64");

  await s3.send(
    new PutObjectCommand({
      Bucket: Resource.MediaBucket.name,
      Key: resultKey,
      Body: imageBuffer,
      ContentType: generatedImage.mediaType ?? "image/png",
    })
  );

  const processingMs = Date.now() - startTime;
  console.log(`Try-on ${tryOnId} completed in ${processingMs}ms`);

  // 5. Update database with result
  await updateTryOnResult(tryOnId, {
    status: "completed",
    resultKey,
    processingMs,
  });

  // 6. Generate style tips
  const tryOnData = await getTryOnForTipGeneration(tryOnId).catch(() => null);

  if (tryOnData) {
    await publish({
      type: "progress",
      tryOnId,
      userId,
      stage: "generating_tips",
      timestamp: Date.now(),
    });

    await generateStyleTips({
      tryOnId,
      garmentName: tryOnData.garment.name,
      garmentCategory: tryOnData.garment.category,
      garmentDescription: tryOnData.garment.description,
      garmentColors: tryOnData.garment.colors,
      bodyProfileFitPreference: tryOnData.bodyProfile.fitPreference,
    }).catch((err) =>
      console.error(`Failed to generate style tips for ${tryOnId}:`, err)
    );
    console.log(`Style tips generated for try-on ${tryOnId}`);
  }

  // Publish complete event after tips
  await publish({
    type: "progress",
    tryOnId,
    userId,
    stage: "complete",
    timestamp: Date.now(),
  });
}

function getMimeTypeFromKey(key: string): string {
  const ext = key.split(".").pop()?.toLowerCase();
  const mimeTypes: Record<string, string> = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    webp: "image/webp",
    gif: "image/gif",
  };
  return mimeTypes[ext ?? ""] ?? "image/jpeg";
}

async function fetchImageAsDataUrl(url: string): Promise<string> {
  // If S3 key, fetch from bucket
  if (url.startsWith("profiles/") || url.startsWith("garments/")) {
    const response = await s3.send(
      new GetObjectCommand({
        Bucket: Resource.MediaBucket.name,
        Key: url,
      })
    );
    const bytes = await response.Body?.transformToByteArray();
    if (!bytes) throw new Error(`Failed to fetch image from S3: ${url}`);
    const base64 = Buffer.from(bytes).toString("base64");
    const mimeType = getMimeTypeFromKey(url);
    return `data:${mimeType};base64,${base64}`;
  }

  // Otherwise fetch from URL
  const response = await fetch(url);
  const buffer = await response.arrayBuffer();
  const base64 = Buffer.from(buffer).toString("base64");
  const contentType = response.headers.get("content-type") ?? "image/jpeg";
  return `data:${contentType};base64,${base64}`;
}
