import { fal } from "@ai-sdk/fal";
import {
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { experimental_generateImage as generateImage } from "ai";
import type { SQSEvent, SQSRecord } from "aws-lambda";
import sharp from "sharp";
import { Resource } from "sst";

import { publishUpscale } from "@/lib/websocket-publisher";
import { updateProfileEnhancement } from "@/services/upscale";

const s3 = new S3Client({});

// FAL AI Recraft Crisp Upscale requires images under 4MP
const MAX_DIMENSION = 1920;
const MAX_PIXELS = 4_000_000;

type UpscaleJobPayload = {
  type: "profile" | "garment" | "tryon";
  entityId: string;
  userId: string;
  sourceImageKey: string;
};

export async function handler(event: SQSEvent): Promise<void> {
  for (const record of event.Records) {
    await processRecord(record);
  }
}

async function processRecord(record: SQSRecord): Promise<void> {
  const payload = JSON.parse(record.body) as UpscaleJobPayload;
  const { type, entityId, userId, sourceImageKey } = payload;
  const startTime = Date.now();

  console.log(`Processing upscale job: ${type}/${entityId}`);

  await publishUpscale({
    type: "upscale_progress",
    entityType: type,
    entityId,
    userId,
    stage: "queued",
    timestamp: Date.now(),
  });

  // 1. Get presigned URL for source image
  await publishUpscale({
    type: "upscale_progress",
    entityType: type,
    entityId,
    userId,
    stage: "fetching",
    timestamp: Date.now(),
  });

  const sourceUrl = await getResizedImageUrl(sourceImageKey);

  // 2. Call FAL AI for upscaling
  await publishUpscale({
    type: "upscale_progress",
    entityType: type,
    entityId,
    userId,
    stage: "upscaling",
    timestamp: Date.now(),
  });

  const { image } = await generateImage({
    model: fal.image("fal-ai/recraft/upscale/crisp"),
    prompt: "",
    providerOptions: {
      fal: {
        imageUrl: sourceUrl,
      },
    },
  });

  if (!image?.base64) {
    if (type === "profile") {
      await updateProfileEnhancement(entityId, {
        status: "FAILED",
        error: "No image generated by upscale model",
      });
    }
    await publishUpscale({
      type: "upscale_progress",
      entityType: type,
      entityId,
      userId,
      stage: "failed",
      timestamp: Date.now(),
      error: "No image generated by upscale model",
    });
    throw new Error("No image generated by upscale model");
  }

  // 3. Upload enhanced image to S3
  await publishUpscale({
    type: "upscale_progress",
    entityType: type,
    entityId,
    userId,
    stage: "uploading",
    timestamp: Date.now(),
  });

  const enhancedKey = getEnhancedKey(type, entityId, sourceImageKey);
  const imageBuffer = Buffer.from(image.base64, "base64");

  await s3.send(
    new PutObjectCommand({
      Bucket: Resource.MediaBucket.name,
      Key: enhancedKey,
      Body: imageBuffer,
      ContentType: image.mediaType ?? "image/png",
    })
  );

  const processingMs = Date.now() - startTime;
  console.log(`Upscale ${type}/${entityId} completed in ${processingMs}ms`);

  // 4. Update database with result
  if (type === "profile") {
    await updateProfileEnhancement(entityId, {
      status: "COMPLETED",
      enhancedKey,
    });
  }

  await publishUpscale({
    type: "upscale_progress",
    entityType: type,
    entityId,
    userId,
    stage: "complete",
    timestamp: Date.now(),
  });
}

async function getPresignedUrl(key: string): Promise<string> {
  const command = new GetObjectCommand({
    Bucket: Resource.MediaBucket.name,
    Key: key,
  });
  return await getSignedUrl(s3, command, { expiresIn: 900 });
}

async function getResizedImageUrl(sourceKey: string): Promise<string> {
  const response = await s3.send(
    new GetObjectCommand({
      Bucket: Resource.MediaBucket.name,
      Key: sourceKey,
    })
  );

  if (!response.Body) {
    throw new Error(`Failed to fetch image: ${sourceKey}`);
  }

  const buffer = Buffer.from(await response.Body.transformToByteArray());

  const metadata = await sharp(buffer).metadata();
  const pixels = (metadata.width ?? 0) * (metadata.height ?? 0);

  if (pixels <= MAX_PIXELS) {
    return getPresignedUrl(sourceKey);
  }

  console.log(
    `Resizing image from ${metadata.width}x${metadata.height} (${pixels} pixels)`
  );

  const resized = await sharp(buffer)
    .resize(MAX_DIMENSION, MAX_DIMENSION, {
      fit: "inside",
      withoutEnlargement: true,
    })
    .jpeg({ quality: 90 })
    .toBuffer();

  const resizedKey = `temp/upscale/${sourceKey.split("/").pop()}`;
  await s3.send(
    new PutObjectCommand({
      Bucket: Resource.MediaBucket.name,
      Key: resizedKey,
      Body: resized,
      ContentType: "image/jpeg",
    })
  );

  return getPresignedUrl(resizedKey);
}

function getEnhancedKey(
  type: string,
  entityId: string,
  sourceKey: string
): string {
  const ext = sourceKey.split(".").pop() ?? "png";
  return `${type}s/${entityId}/enhanced.${ext}`;
}
