/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as TodoTodoIdRouteImport } from './routes/todo/$todoId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as authedSupportRouteImport } from './routes/(authed)/support'
import { Route as authedDashboardRouteRouteImport } from './routes/(authed)/dashboard/route'
import { Route as authedTryOnIndexRouteImport } from './routes/(authed)/try-on/index'
import { Route as authedSettingsIndexRouteImport } from './routes/(authed)/settings/index'
import { Route as authedProfileIndexRouteImport } from './routes/(authed)/profile/index'
import { Route as authedLookbooksIndexRouteImport } from './routes/(authed)/lookbooks/index'
import { Route as authedGarmentIndexRouteImport } from './routes/(authed)/garment/index'
import { Route as authedDashboardIndexRouteImport } from './routes/(authed)/dashboard/index'
import { Route as authedCatalogIndexRouteImport } from './routes/(authed)/catalog/index'
import { Route as SharedLookbookLookbookIdRouteImport } from './routes/shared/lookbook/$lookbookId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authedTryOnTryOnIdRouteImport } from './routes/(authed)/try-on/$tryOnId'
import { Route as authedProfileNewRouteImport } from './routes/(authed)/profile/new'
import { Route as authedProfileProfileIdRouteImport } from './routes/(authed)/profile/$profileId'
import { Route as authedLookbooksLookbookIdRouteImport } from './routes/(authed)/lookbooks/$lookbookId'
import { Route as authedGarmentNewRouteImport } from './routes/(authed)/garment/new'
import { Route as authedGarmentGarmentIdRouteImport } from './routes/(authed)/garment/$garmentId'
import { Route as authedCatalogGarmentGarmentIdRouteImport } from './routes/(authed)/catalog/garment/$garmentId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoTodoIdRoute = TodoTodoIdRouteImport.update({
  id: '/todo/$todoId',
  path: '/todo/$todoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authedSupportRoute = authedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedDashboardRouteRoute = authedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedTryOnIndexRoute = authedTryOnIndexRouteImport.update({
  id: '/try-on/',
  path: '/try-on/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSettingsIndexRoute = authedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedProfileIndexRoute = authedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedLookbooksIndexRoute = authedLookbooksIndexRouteImport.update({
  id: '/lookbooks/',
  path: '/lookbooks/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedGarmentIndexRoute = authedGarmentIndexRouteImport.update({
  id: '/garment/',
  path: '/garment/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedDashboardIndexRoute = authedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedDashboardRouteRoute,
} as any)
const authedCatalogIndexRoute = authedCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => authedRouteRoute,
} as any)
const SharedLookbookLookbookIdRoute =
  SharedLookbookLookbookIdRouteImport.update({
    id: '/shared/lookbook/$lookbookId',
    path: '/shared/lookbook/$lookbookId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authedTryOnTryOnIdRoute = authedTryOnTryOnIdRouteImport.update({
  id: '/try-on/$tryOnId',
  path: '/try-on/$tryOnId',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedProfileNewRoute = authedProfileNewRouteImport.update({
  id: '/profile/new',
  path: '/profile/new',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedProfileProfileIdRoute = authedProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedLookbooksLookbookIdRoute =
  authedLookbooksLookbookIdRouteImport.update({
    id: '/lookbooks/$lookbookId',
    path: '/lookbooks/$lookbookId',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedGarmentNewRoute = authedGarmentNewRouteImport.update({
  id: '/garment/new',
  path: '/garment/new',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedGarmentGarmentIdRoute = authedGarmentGarmentIdRouteImport.update({
  id: '/garment/$garmentId',
  path: '/garment/$garmentId',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedCatalogGarmentGarmentIdRoute =
  authedCatalogGarmentGarmentIdRouteImport.update({
    id: '/catalog/garment/$garmentId',
    path: '/catalog/garment/$garmentId',
    getParentRoute: () => authedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard': typeof authedDashboardRouteRouteWithChildren
  '/support': typeof authedSupportRoute
  '/auth/signup': typeof AuthSignupRoute
  '/todo/$todoId': typeof TodoTodoIdRoute
  '/auth': typeof AuthIndexRoute
  '/garment/$garmentId': typeof authedGarmentGarmentIdRoute
  '/garment/new': typeof authedGarmentNewRoute
  '/lookbooks/$lookbookId': typeof authedLookbooksLookbookIdRoute
  '/profile/$profileId': typeof authedProfileProfileIdRoute
  '/profile/new': typeof authedProfileNewRoute
  '/try-on/$tryOnId': typeof authedTryOnTryOnIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/shared/lookbook/$lookbookId': typeof SharedLookbookLookbookIdRoute
  '/catalog': typeof authedCatalogIndexRoute
  '/dashboard/': typeof authedDashboardIndexRoute
  '/garment': typeof authedGarmentIndexRoute
  '/lookbooks': typeof authedLookbooksIndexRoute
  '/profile': typeof authedProfileIndexRoute
  '/settings': typeof authedSettingsIndexRoute
  '/try-on': typeof authedTryOnIndexRoute
  '/catalog/garment/$garmentId': typeof authedCatalogGarmentGarmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/support': typeof authedSupportRoute
  '/auth/signup': typeof AuthSignupRoute
  '/todo/$todoId': typeof TodoTodoIdRoute
  '/auth': typeof AuthIndexRoute
  '/garment/$garmentId': typeof authedGarmentGarmentIdRoute
  '/garment/new': typeof authedGarmentNewRoute
  '/lookbooks/$lookbookId': typeof authedLookbooksLookbookIdRoute
  '/profile/$profileId': typeof authedProfileProfileIdRoute
  '/profile/new': typeof authedProfileNewRoute
  '/try-on/$tryOnId': typeof authedTryOnTryOnIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/shared/lookbook/$lookbookId': typeof SharedLookbookLookbookIdRoute
  '/catalog': typeof authedCatalogIndexRoute
  '/dashboard': typeof authedDashboardIndexRoute
  '/garment': typeof authedGarmentIndexRoute
  '/lookbooks': typeof authedLookbooksIndexRoute
  '/profile': typeof authedProfileIndexRoute
  '/settings': typeof authedSettingsIndexRoute
  '/try-on': typeof authedTryOnIndexRoute
  '/catalog/garment/$garmentId': typeof authedCatalogGarmentGarmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authed)': typeof authedRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/(authed)/dashboard': typeof authedDashboardRouteRouteWithChildren
  '/(authed)/support': typeof authedSupportRoute
  '/auth/signup': typeof AuthSignupRoute
  '/todo/$todoId': typeof TodoTodoIdRoute
  '/auth/': typeof AuthIndexRoute
  '/(authed)/garment/$garmentId': typeof authedGarmentGarmentIdRoute
  '/(authed)/garment/new': typeof authedGarmentNewRoute
  '/(authed)/lookbooks/$lookbookId': typeof authedLookbooksLookbookIdRoute
  '/(authed)/profile/$profileId': typeof authedProfileProfileIdRoute
  '/(authed)/profile/new': typeof authedProfileNewRoute
  '/(authed)/try-on/$tryOnId': typeof authedTryOnTryOnIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/shared/lookbook/$lookbookId': typeof SharedLookbookLookbookIdRoute
  '/(authed)/catalog/': typeof authedCatalogIndexRoute
  '/(authed)/dashboard/': typeof authedDashboardIndexRoute
  '/(authed)/garment/': typeof authedGarmentIndexRoute
  '/(authed)/lookbooks/': typeof authedLookbooksIndexRoute
  '/(authed)/profile/': typeof authedProfileIndexRoute
  '/(authed)/settings/': typeof authedSettingsIndexRoute
  '/(authed)/try-on/': typeof authedTryOnIndexRoute
  '/(authed)/catalog/garment/$garmentId': typeof authedCatalogGarmentGarmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard'
    | '/support'
    | '/auth/signup'
    | '/todo/$todoId'
    | '/auth'
    | '/garment/$garmentId'
    | '/garment/new'
    | '/lookbooks/$lookbookId'
    | '/profile/$profileId'
    | '/profile/new'
    | '/try-on/$tryOnId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/shared/lookbook/$lookbookId'
    | '/catalog'
    | '/dashboard/'
    | '/garment'
    | '/lookbooks'
    | '/profile'
    | '/settings'
    | '/try-on'
    | '/catalog/garment/$garmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/support'
    | '/auth/signup'
    | '/todo/$todoId'
    | '/auth'
    | '/garment/$garmentId'
    | '/garment/new'
    | '/lookbooks/$lookbookId'
    | '/profile/$profileId'
    | '/profile/new'
    | '/try-on/$tryOnId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/shared/lookbook/$lookbookId'
    | '/catalog'
    | '/dashboard'
    | '/garment'
    | '/lookbooks'
    | '/profile'
    | '/settings'
    | '/try-on'
    | '/catalog/garment/$garmentId'
  id:
    | '__root__'
    | '/'
    | '/(authed)'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/(authed)/dashboard'
    | '/(authed)/support'
    | '/auth/signup'
    | '/todo/$todoId'
    | '/auth/'
    | '/(authed)/garment/$garmentId'
    | '/(authed)/garment/new'
    | '/(authed)/lookbooks/$lookbookId'
    | '/(authed)/profile/$profileId'
    | '/(authed)/profile/new'
    | '/(authed)/try-on/$tryOnId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/shared/lookbook/$lookbookId'
    | '/(authed)/catalog/'
    | '/(authed)/dashboard/'
    | '/(authed)/garment/'
    | '/(authed)/lookbooks/'
    | '/(authed)/profile/'
    | '/(authed)/settings/'
    | '/(authed)/try-on/'
    | '/(authed)/catalog/garment/$garmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authedRouteRoute: typeof authedRouteRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthSignupRoute: typeof AuthSignupRoute
  TodoTodoIdRoute: typeof TodoTodoIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  SharedLookbookLookbookIdRoute: typeof SharedLookbookLookbookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/$todoId': {
      id: '/todo/$todoId'
      path: '/todo/$todoId'
      fullPath: '/todo/$todoId'
      preLoaderRoute: typeof TodoTodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/support': {
      id: '/(authed)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof authedSupportRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/dashboard': {
      id: '/(authed)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authedDashboardRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/try-on/': {
      id: '/(authed)/try-on/'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof authedTryOnIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/settings/': {
      id: '/(authed)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authedSettingsIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/profile/': {
      id: '/(authed)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authedProfileIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/lookbooks/': {
      id: '/(authed)/lookbooks/'
      path: '/lookbooks'
      fullPath: '/lookbooks'
      preLoaderRoute: typeof authedLookbooksIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/garment/': {
      id: '/(authed)/garment/'
      path: '/garment'
      fullPath: '/garment'
      preLoaderRoute: typeof authedGarmentIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/dashboard/': {
      id: '/(authed)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authedDashboardIndexRouteImport
      parentRoute: typeof authedDashboardRouteRoute
    }
    '/(authed)/catalog/': {
      id: '/(authed)/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof authedCatalogIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/shared/lookbook/$lookbookId': {
      id: '/shared/lookbook/$lookbookId'
      path: '/shared/lookbook/$lookbookId'
      fullPath: '/shared/lookbook/$lookbookId'
      preLoaderRoute: typeof SharedLookbookLookbookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/try-on/$tryOnId': {
      id: '/(authed)/try-on/$tryOnId'
      path: '/try-on/$tryOnId'
      fullPath: '/try-on/$tryOnId'
      preLoaderRoute: typeof authedTryOnTryOnIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/profile/new': {
      id: '/(authed)/profile/new'
      path: '/profile/new'
      fullPath: '/profile/new'
      preLoaderRoute: typeof authedProfileNewRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/profile/$profileId': {
      id: '/(authed)/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof authedProfileProfileIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/lookbooks/$lookbookId': {
      id: '/(authed)/lookbooks/$lookbookId'
      path: '/lookbooks/$lookbookId'
      fullPath: '/lookbooks/$lookbookId'
      preLoaderRoute: typeof authedLookbooksLookbookIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/garment/new': {
      id: '/(authed)/garment/new'
      path: '/garment/new'
      fullPath: '/garment/new'
      preLoaderRoute: typeof authedGarmentNewRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/garment/$garmentId': {
      id: '/(authed)/garment/$garmentId'
      path: '/garment/$garmentId'
      fullPath: '/garment/$garmentId'
      preLoaderRoute: typeof authedGarmentGarmentIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/catalog/garment/$garmentId': {
      id: '/(authed)/catalog/garment/$garmentId'
      path: '/catalog/garment/$garmentId'
      fullPath: '/catalog/garment/$garmentId'
      preLoaderRoute: typeof authedCatalogGarmentGarmentIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
  }
}

interface authedDashboardRouteRouteChildren {
  authedDashboardIndexRoute: typeof authedDashboardIndexRoute
}

const authedDashboardRouteRouteChildren: authedDashboardRouteRouteChildren = {
  authedDashboardIndexRoute: authedDashboardIndexRoute,
}

const authedDashboardRouteRouteWithChildren =
  authedDashboardRouteRoute._addFileChildren(authedDashboardRouteRouteChildren)

interface authedRouteRouteChildren {
  authedDashboardRouteRoute: typeof authedDashboardRouteRouteWithChildren
  authedSupportRoute: typeof authedSupportRoute
  authedGarmentGarmentIdRoute: typeof authedGarmentGarmentIdRoute
  authedGarmentNewRoute: typeof authedGarmentNewRoute
  authedLookbooksLookbookIdRoute: typeof authedLookbooksLookbookIdRoute
  authedProfileProfileIdRoute: typeof authedProfileProfileIdRoute
  authedProfileNewRoute: typeof authedProfileNewRoute
  authedTryOnTryOnIdRoute: typeof authedTryOnTryOnIdRoute
  authedCatalogIndexRoute: typeof authedCatalogIndexRoute
  authedGarmentIndexRoute: typeof authedGarmentIndexRoute
  authedLookbooksIndexRoute: typeof authedLookbooksIndexRoute
  authedProfileIndexRoute: typeof authedProfileIndexRoute
  authedSettingsIndexRoute: typeof authedSettingsIndexRoute
  authedTryOnIndexRoute: typeof authedTryOnIndexRoute
  authedCatalogGarmentGarmentIdRoute: typeof authedCatalogGarmentGarmentIdRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedDashboardRouteRoute: authedDashboardRouteRouteWithChildren,
  authedSupportRoute: authedSupportRoute,
  authedGarmentGarmentIdRoute: authedGarmentGarmentIdRoute,
  authedGarmentNewRoute: authedGarmentNewRoute,
  authedLookbooksLookbookIdRoute: authedLookbooksLookbookIdRoute,
  authedProfileProfileIdRoute: authedProfileProfileIdRoute,
  authedProfileNewRoute: authedProfileNewRoute,
  authedTryOnTryOnIdRoute: authedTryOnTryOnIdRoute,
  authedCatalogIndexRoute: authedCatalogIndexRoute,
  authedGarmentIndexRoute: authedGarmentIndexRoute,
  authedLookbooksIndexRoute: authedLookbooksIndexRoute,
  authedProfileIndexRoute: authedProfileIndexRoute,
  authedSettingsIndexRoute: authedSettingsIndexRoute,
  authedTryOnIndexRoute: authedTryOnIndexRoute,
  authedCatalogGarmentGarmentIdRoute: authedCatalogGarmentGarmentIdRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authedRouteRoute: authedRouteRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthSignupRoute: AuthSignupRoute,
  TodoTodoIdRoute: TodoTodoIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  SharedLookbookLookbookIdRoute: SharedLookbookLookbookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
